org: georgedavis
app: aws-cloudwatch-logs-retention
service: aws-cloudwatch-logs-retention

frameworkVersion: '3'

custom:
  defaultStage: dev
  stages:
    dev:
      profile: default
      stackDeploymentRegion: us-east-2
      regionList: us-east-1,us-east-2,us-west-1,us-west-2,ca-central-1
      exceptionLogGroups: filestoragesecurity-ingestbucket,filestoragesecurity-ingestbucket-2,filestoragesecurity-ingestbucket-3-ca
      defaultLogRetentionInDays: 14
    prod:
      profile: serverless
      stackDeploymentRegion: us-east-1
      regionList: us-east-1,us-east-2,us-west-1,us-west-2,ca-central-1
      exceptionLogGroups: serverless-cloudone
      defaultLogRetentionInDays: 14

provider:
  name: aws
  runtime: python3.8
  profile: ${self:custom.stages.${opt:stage}.profile}
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${self:custom.stages.${opt:stage}.stackDeploymentRegion}
  memorySize: 128
  timeout: 300
  logRetentionInDays: 14
  environment:
    regionList: us-east-1,us-east-2,us-west-1,us-west-2,ca-central-1
    exceptionLogGroups: serverless-cloudone
    logRetentionInDays: 14
  tags:
    BusinessCase: aws-cloudwatch-logs-retention
    Owner: TrendMicro
    CodeSource: https://github.com/GeorgeDavis-TM/aws-cloudwatch-logs-retention.git
  stackTags:
    BusinessCase: aws-cloudwatch-logs-retention
    Owner: TrendMicro
    CodeSource: https://github.com/GeorgeDavis-TM/aws-cloudwatch-logs-retention.git
  iam:
    role:
      name: aws-cloudwatch-logs-retention-${opt:stage, self:custom.defaultStage}
      path: /
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action:
            - 'logs:*'
      tags:
        BusinessCase: aws-cloudwatch-logs-retention
        Owner: TrendMicro
        CodeSource: https://github.com/GeorgeDavis-TM/aws-cloudwatch-logs-retention.git

functions:
  main:
    handler: handler.main
    description: Scheduled run of aws-cloudwatch-logs-retention Cleanup Tasks    
    events:
      - schedule:
          name: scheduled-aws-cloudwatch-logs-retention-${opt:stage, self:custom.defaultStage}
          description: 'aws-cloudwatch-logs-retention Cleanup Tasks Run Schedule'
          rate: cron(0 23 1 * ? *)